name: CI

on: [push, pull_request]

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make BUILD_TLS=yes
      run: |
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make -j2
    - name: test-tls
      run: |
        sudo apt-get -y install tcl8.5 tcl-tls
        ./utils/gen-test-certs.sh
        ./runtest --clients 2 --verbose --tls
    - name: test
        ./runtest --clients 2 --verbose
    - name: cluster-test
      run: |
        ./runtest-cluster
    - name: sentinel test
      run: |
          ./runtest-sentinel
    - name: module tests
      run: |
          ./runtest-moduleapi

        
  test-ubuntu-arm:
    runs-on: [self-hosted, linux, arm]
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make -j4
    - name: test
      run: |
        sudo apt-get -y install tcl8.5
        ./runtest --clients 2 --verbose
    - name: module tests
      run: |
          ./runtest-moduleapi

  build-ubuntu-old:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: make -j2
      run: | 
        sudo apt-get -y install uuid-dev libcurl4-openssl-dev
        make

  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make -j2
